// User action constants
export const AUTH_LOGGED_IN = 'AUTH_LOGGED_IN';
export const AUTH_LOGGED_OUT = 'AUTH_LOGGED_OUT';
export const AUTH_CHECK_AUTH = 'AUTH_CHECK_AUTH';
export const AUTH_LOGIN_PENDING = 'AUTH_LOGIN_PENDING';

// Notification action constants
export const NOTIFICATION_DISPLAY_ERROR = 'DISPLAY_ERROR';
export const NOTIFICATION_CONFIRM_RESET_PASSWORD = 'CONFIRM_RESET_PASSWORD';
export const NOTIFICATION_ADD = 'NOTIFICATION_ADD';
export const NOTIFICATION_REMOVE = 'NOTIFICATION_REMOVE';

// Rules (Products)
export const SET_ALL_RULES = 'SET_ALL_RULES';
export const ADD_RULE = 'ADD_RULE';
export const UPDATE_RULES = 'UPDATE_RULES';
export const DELETE_RULE = 'DELETE_RULE';
export const SHOW_RULES_LOADING = 'SHOW_RULES_LOADING';

// Modals
export const MODAL_CLOSE_MODAL = 'MODAL_CLOSE_MODAL';
export const MODAL_SET_MODAL = 'MODAL_SET_MODAL';
export const MODAL_SET_IMAGE_CONTEXT = 'MODAL_SET_IMAGE_CONTEXT';

// Routes
export const ROUTER_LOCATION_CHANGE = '@@router/LOCATION_CHANGE';
export const ROUTER_CHANGE_ROUTE = 'CHANGE_ROUTE';
export const ROUTER_REDIRECT_IN_PROGRESS = 'ROUTER_REDIRECT_IN_PROGRESS';

// Request status
export const REQUEST_START = 'REQUEST_START';
export const REQUEST_END = 'REQUEST_END';
export const REQUEST_FAILED = 'REQUEST_FAILED';
